### ISSUE TITLE
Update Readme section

### ISSUE THREAD

**Issue by suhanipaliwal** [hasmithagunda123/ALL_INDIA_HACKATHON#1]
I would like to update the Readme section. I want to organise the Readme section so that the project can be understood in a better way. Please assign me this issue.

**Comment by aditi1807** [comment]
Hey,
I am an aspiring ML engineer and have done a project on this topic could you please assign me this issue so i can add real values

**Comment by yashbalpande** [comment]
Hey Hasmitha,
i have experience in ml we have make this things even more accurate and can add more things into like like Human Behavior Detection Please Assign this to me...   Assign me this issue under GSSoC 24.

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in ML. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
Plz assign this to me..

**Comment by poojaharihar03** [comment]
Hey Hasmitha,
I am currently working in ai/ml. Assign me this issue under GSSoC'24.
Starting with the readme and then working on the accuracy of the detection.
Looking forward to working on this project!

**Comment by code-with-aneesh** [comment]
I'd like to take on the task of organizing the Readme section to enhance project understanding. Please assign me this issue as I believe I can improve the clarity and structure effectively.

**Comment by Anjalipriya03** [comment]
Hi!
I would like to work on this issue please assign it to me under gssoc 24.

**Comment by shrehs** [comment]
Hello @hasmithagunda123,
I would love to work on the issue. If you could assign it to me it would be great.

**Comment by hasmithagunda123** [comment]
Hello I would like to work on this issue please assign it to me

**Comment by vmalani27** [comment]
HI, I am an aspiring contributor under gssoc 2024, i would like to update the readme section so that it is more visible and less cluttered to read and easy to understand, please assign this issue to me under gssoc 2024
will do my best

**Comment by akshatsharma2407** [comment]
Hello, I am fully capable of updating your README section as a GSSoC contributor. Kindly assign me this issue as I possess intermediate knowledge of the technology utilized in your project. I am confident that I am the best fit for this task.

**Comment by Siddharth9987** [comment]
I would like to work on this issue please assign it to me.

**Comment by pavitraag** [comment]
I would like to make your README file better ,can you please assign me for updating your README file

**Comment by Tanu-120** [comment]
Hello,
I would like to improve this README file better, Can you please assign to me.Please.

**Comment by anoushkaacc** [comment]
Hey, I would like to improve the README file. I would make the file easier to understand for future developers. Please assign me this issue.

**Comment by 21wh1a6654** [comment]
Hello,
I would like to work on this README file better, Can you please assign to me.

**Comment by MohanRamSridhar** [comment]
I would like to further enhance by adding images for clarity the Readme file can you please assign this to me

**Comment by hasmithagunda123** [comment]
@MohanRamSridhar  okk assigned
