### ISSUE TITLE
Preserving Privacy: Safeguarding Personal Data in Surveillance Systems

### ISSUE THREAD

**Issue by Harihara04sudhan** [hasmithagunda123/ALL_INDIA_HACKATHON#12]
Hi @hasmithagunda123 ,

I'm excited to be part of this initiative aimed at safeguarding individual privacy within surveillance systems, particularly in addressing gender-based violence. Our focus will be on implementing transparent data collection practices, enhancing security measures, and establishing mechanisms for accountability and empowerment.

By prioritizing privacy, we strive to strike a delicate balance between public safety and the protection of individual rights. I'm eager to contribute to this important cause and ensure that our efforts make a meaningful impact.

Thank you for considering my involvement in this initiative.

**Comment by Harihara04sudhan** [comment]
Please  assign me this issue so that i can start working on it!

**Comment by Shravani246** [comment]
@hasmithagunda123 assign me this issue i can complete it.

**Comment by PriyanshuSharma1** [comment]
@hasmithagunda123  I am the right person for this. I have done similar project in the past. Can you assign me this issue?

**Comment by Raghucharan16** [comment]
The flow should be capturing the frames and converting them into features vectors and monitoring the people's behavioral activity thus raising an alert to nearby places if unwanted behavior is noticed. so that we don't actually store the facial data but the feature vectors. I think i can give a headstart to this as i'm familiar with aws and different face recognition and facial attribute activity libraries so if it isn't assigned, sign me in.

**Comment by LulwaAnif** [comment]
Please assign me this issue so that i can start working on it! I am enthusiastic about contributing to our team and believe my skills in Python programming would be beneficial.

**Comment by kart2004** [comment]
Hi @hasmithagunda123, Can you please assign this to me I think I can get it done properly.
Thanks in advance

**Comment by rimjhimsingh2308** [comment]
Hi @hasmithagunda123 can u assign this issue to me ? i am exploring and trying to work on machine learning . I am willing to work on this issue as it is quite interesting . this is my profile link : https://www.linkedin.com/in/rimjhim-singh-182876216/
