### ISSUE TITLE
Steps for contributing in CONTIBUTING.md file

### ISSUE THREAD

**Issue by riteshpushkar** [hasmithagunda123/ALL_INDIA_HACKATHON#17]
I will be adding all the steps in detail like 
fork
clone 
branch change
add
commit
push 
how to create pr 
I'll be explaining everything in details to contibutors new to open source 
pls assign me this under label gssoc24

**Comment by Akshitha28112004** [comment]
Hey, I've already contributed to another project so I can do this. Can you please assign me this issue under gssoc'24?

**Comment by Jhalak-Gupta** [comment]
I am interested in this task. Pls assign it to me under GSSOC'24 so that I can contribute to this project. I am good enough at my skills to complete this task efficiently.

**Comment by SuhaniStark** [comment]
Could you please assign this issue to me under GSSOC'24.

**Comment by khushikunte** [comment]
Hello,I am interested in this task I would like to work on this .Please assign me this Under GSSOC'24

**Comment by tejj74** [comment]
since I'm a begginer too, I know how important it is to know how to contribute in an OS, I can very much relate to the new users , I would like to work on this issue ,Please assign this issue to me @TAHIR0110
