### ISSUE TITLE
Update README.md for Users to clone this repository

### ISSUE THREAD

**Issue by amroodh** [hasmithagunda123/ALL_INDIA_HACKATHON#19]
Greeting PA,
1) The Readme file lacks the list of python libraries to be installed. The best solution would be to create a requirement.txt file and step to install them.
2) The steps required to Fork and clone the repo is not available for new contributors.

**Comment by amroodh** [comment]
Please assign me this issue

**Comment by prajwaldp223** [comment]
can i do it?

**Comment by Prashant-2024** [comment]
i would like to request to assign this issue to me under GSSOC'24

**Comment by Akshitha28112004** [comment]
Hey, can you please assign me this issue under gssoc'24?

**Comment by Jhalak-Gupta** [comment]
I am interested in this task. Pls assign it to me under GSSOC'24 so that I can contribute to this project. I am good enough at my skills to complete this task efficiently.

**Comment by AtharvaSonar-21** [comment]
I would like to work on this feature @hasmithagunda123  please assign it to me.

**Comment by SuhaniStark** [comment]
Could you please assign this issue to me under GSSOC'24.

**Comment by aursh24** [comment]
Please assign me the 2nd issue of "Forking and Cloning Repo" under GSSOC'24.

**Comment by Prashant-2024** [comment]
i would like to request to assign this issue to me under GSSOC'24

**Comment by psyuktha** [comment]
can you assign me for this @hasmithagunda123

**Comment by sreesti07** [comment]
Hello @hasmithagunda123, I would like to work on this issue as a contributor at GSSOC'24. Please assign this to me.

**Comment by Harshita297** [comment]
Hii @hasmithagunda123 
Please assign this task to me under GSSOC'24

**Comment by khushikunte** [comment]
Hii.I would like to work on this .Please assign this to me Under GSSOC'24

**Comment by divyadaya** [comment]
@hasmithagunda123 , I would like to request assignment of this issue to me under GSSoC'24.

**Comment by aRUsh-codes** [comment]
Hi, @hasmithagunda123 I think I can create the requirements.txt file and also manage to list the steps for further checking if it worked safely.
Please assign me this issue

**Comment by Vallika09** [comment]
I would like to work on this. Please assign this to me as a contributor at GSSOC'24.

**Comment by lassmara** [comment]
Please assign me this issue.

**Comment by TushtiSavarn** [comment]
hi @hasmithagunda123 
**Proposal for Adding More Examples to Prompt Example Page**

**Objective**:
The current Prompt Example page lacks comprehensive coverage and user-friendliness. By adding more examples and enhancing the formatting, we aim to improve user understanding and utilization of the application's features.

**Tasks**:

1. **Add Additional Examples**:
   - Incorporate diverse examples covering various use cases.
   - Ensure clear instructions accompany each example.

2. **Improve Formatting**:
   - Organize content with headings, subheadings, and lists for clarity.
   - Integrate code snippets or sample inputs/outputs where applicable.

3. **Ensure Consistency**:
   - Maintain a consistent style and format across all examples.

**Conclusion**:
Enhancing the Prompt Example page will enhance user experience and usability, fostering better interaction with the application. This proposal outlines a concise plan for achieving these goals within a reasonable timeline.
