### ISSUE TITLE
add a feature

### ISSUE THREAD

**Issue by yashbalpande** [hasmithagunda123/ALL_INDIA_HACKATHON#2]
Hey ,
i have experience in ml we have make this things even more accurate and can add more things into like like Human Behavior Detection Please Assign this to me... Assign me this issue under GSSoC 24.

**Comment by bhartijoshi04** [comment]
Hi, I am learning ML and consistently looking for hands-on experience. I think through gsssoc'24, I can make that happen.
I would like to contribute to this project and learn effectively. This project interests me the most. I am skilled in data analysis
Looking forward to it.

**Comment by ghost** [comment]
Hello, I hope this message finds you well. I am well experienced in python with 5 stars in hackerrank and consistently learning ML. I want to gain hands on experience by contributing to this project through GSSOC'24. Please give me opportunity to contribute to this project. I hold a google data analytics course certificate of 6 months too

**Comment by Erkajalkri** [comment]
I am well in python. I want to do this project through GSSOC'24.

**Comment by ghost** [comment]
Hello
I am a GSSoC'24 contributor and looking forward to work on this

**Comment by Erkajalkri** [comment]
Yes

**Comment by Satyaas1117** [comment]
@hasmithagunda123 kindly mention the GSSOC with level1 , level2 and level3. So that we can contribute further.

**Comment by Erkajalkri** [comment]
Level 1

**Comment by ajayprataptomar** [comment]
Hello, I am a GSSoC'24 contributor looking forward to working on level 1. please assign me an issue

**Comment by richardar** [comment]
Hey there , could you kindly assign me this issue, i have some exciting ideas that I would like to implement

**Comment by anupa-rb** [comment]
Hi there, I've been learning python and I'm looking forward to contributing to this project through GSSOC'24. Please assign this issue to me.

**Comment by Aditi22Bansal** [comment]
Hi there, I've good knowledge in python and I'm interested in contributing to this project through GSSOC'24. Please assign this issue to me.

**Comment by Neh2005** [comment]
Hi there, I'm excited to contribute to this project through GSSOC'24. I've been learning Python. Kindly assign this issue to me.

**Comment by AYUSHIIESTS** [comment]
Hello
I am a GSSoC'24 contributor and looking forward to work on this

**Comment by rahulnarayaniitk** [comment]
hello @hasmithagunda123,
I wish to make my contribution to this open-source project for GSSoC' 24. 
I am currently doing a project on the topic of DRQN-based 3D Obstacle Avoidance with a Limited Field of View and I think I can use my experience by adding some features to this project to make it more accurate and efficient.
Therefore, kindly assign this issue to me.
