### ISSUE TITLE
Hosting it to Streamlit or gradio

### ISSUE THREAD

**Issue by SaranDharshanSP** [hasmithagunda123/ALL_INDIA_HACKATHON#23]
This is a good project but to view this , people have to download the code or see the video. We could host it in Gradio or streamlit and try in our gallery videos too. Under Gssoc 24 assign this to me please. I am well versed in AI and ML and DL.

**Comment by AryanGupta-12** [comment]
hello sir @SaranDharshanSP , I have already deployed many projects on streamlit and gradio, please assign me this project under GSSOC 24.

**Comment by Cralsic123** [comment]
Hello @hasmithagunda123 you can check my repos, I have hosted many ML web apps on Streamlit and have a decent knowledge about it. Would love to contribute on it.

**Comment by SaranDharshanSP** [comment]
I don't find the model.h5 file in the repo for giving it to streamlit
