### ISSUE TITLE
add code of conduct file

### ISSUE THREAD

**Issue by yashbalpande** [hasmithagunda123/ALL_INDIA_HACKATHON#3]
please assign this issue to me under GSSOC 2024

**Comment by Priyanshu2631** [comment]
I would like to work on this issue, please assign to me for GSSOC 2024. I hv written such documentation in my previous pursuits.

**Comment by shrehs** [comment]
I would love to work on this if assigned under GSSOC 24. I would love to do documentation for the project.

**Comment by ghost** [comment]
Hello
I am a GSSoC'24 contributor and looking forward to work on this

**Comment by ajayprataptomar** [comment]
Hello, I am a GSSoC'24 contributor and looking forward to working on level 1

**Comment by saurabh-Sahu16** [comment]
Hello
I am a GSSoC'24 contributor and looking forward to work on this

**Comment by hasmithagunda123** [comment]
Closed the issue
