### ISSUE TITLE
Create an streamlit app to detect face

### ISSUE THREAD

**Issue by Cralsic123** [hasmithagunda123/ALL_INDIA_HACKATHON#33]
To enhance visual detection in airports and other regions, we will have a database of facial images.
 If a person we want to find is tagged in the database then when we pass a video or picture the algorithm will match the face and try to find the required data from the database and we will fetch it and show it to the user. Easier criminal detection.

**Comment by Cralsic123** [comment]
I have prior experience in face detection, voice detection algorithms.  I have worked with DELF and YOLO and other image feature matching algorithms. I would love to work on this issue. @hasmithagunda123 I would like to contribute here, please assign me this task.

**Comment by riteshpushkar** [comment]
I am currently learning face and voice detection algos so It would be great for my learning if 
I'm assigned also this under gssoc24 @hasmithagunda123
