### ISSUE TITLE
Not able to view the Jupyter File

### ISSUE THREAD

**Issue by Adii2202** [hasmithagunda123/ALL_INDIA_HACKATHON#38]
JSON Error
![image](https://github.com/hasmithagunda123/ALL_INDIA_HACKATHON/assets/131331573/e33fa8fd-404f-4853-ab68-91f47890b336)

**Comment by hasmithagunda123** [comment]
now its working fine once check

**Comment by Adii2202** [comment]
> now its working fine once check
yes thank you
