### ISSUE TITLE
[Feat]: Workflow for closing Old PRs

### ISSUE THREAD

**Issue by Asymtode712** [hasmithagunda123/ALL_INDIA_HACKATHON#52]
This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

@hasmithagunda123 please assign me this issue under gssoc'24

**Comment by Asymtode712** [comment]
@hasmithagunda123 please assign me this issue under gssoc'24

**Comment by MohanRamSridhar** [comment]
@hasmithagunda123 can you please assign me this issue cause I have required experience as you can see in my profile

**Comment by Asymtode712** [comment]
@MohanRamSridhar this issue has been already raised and authored by me
