### ISSUE TITLE
[Feat]: Auto commenting on closing an issue

### ISSUE THREAD

**Issue by Asymtode712** [hasmithagunda123/ALL_INDIA_HACKATHON#53]
# Description

This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.

# Screenshot

![issue closed](https://github.com/hasmithagunda123/ALL_INDIA_HACKATHON/assets/115717746/d7cfd125-1345-4950-87fc-4eaa077933e0)

**Comment by Asymtode712** [comment]
@hasmithagunda123 please assign me this issue under gssoc'24

**Comment by Asymtode712** [comment]
@hasmithagunda123 what's the reason?

**Comment by hasmithagunda123** [comment]
#50 is same

**Comment by Asymtode712** [comment]
@hasmithagunda123 #50 is meant for PR and this is meant for issue, both are different and both workflows are diiferent so please assign me

**Comment by Asymtode712** [comment]
@hasmithagunda123 please add 'gssoc' and level labels
