### ISSUE TITLE
Update Contribution Guidelines

### ISSUE THREAD

**Issue by Zoha-Waheed** [hasmithagunda123/ALL_INDIA_HACKATHON#57]
The README does not provide clear guidelines for contributing to the project.

Assign this issue to me. 

I will add`CONTRIBUTING.md` file with instructions on how to contribute, including coding standards, how to submit pull requests, and how to report issues.

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Zoha-Waheed** [comment]
Contributing.md file has been updated, committed and successfully merged to main.
