### ISSUE TITLE
Tampering on the CCTV's.

### ISSUE THREAD

**Issue by Adii2202** [hasmithagunda123/ALL_INDIA_HACKATHON#6]
Tampering of cctv is illegal which must be reported immediately. 
A siren would be added if cctv is tampered.

Assign this to me under GSSOC '24

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.

**Comment by Adii2202** [comment]
I am a contributor not a mentor

**Comment by SDprogramer** [comment]
We can both work on this issue

**Comment by Adii2202** [comment]
works
Assign us so that we can begin

**Comment by Adii2202** [comment]
For merging of the tampering of the CCTV code into the main ipynb file I will need the model.h5 file to check whether its giving sirens or not
TIll then I can create a folder and add the tampering python file and siren into it
