### ISSUE TITLE
Integrate Facial Expression Recognition Model with Surveillance System

### ISSUE THREAD

**Issue by revanth1718** [hasmithagunda123/ALL_INDIA_HACKATHON#66]
I have a pre-trained facial expression recognition model, built using PyTorch, which can identify threatening expressions and potential risks. We need to integrate this model into the surveillance system to detect and respond to threats in real-time.

I am Participating in GSSOC'24.

Assign this issue to me. @hasmithagunda123

**Comment by riteshpushkar** [comment]
I would also love to work in this issue caould you pls provide me this under gssoc24
