### ISSUE TITLE
[doc]: Enhancing few sections in readme document.

### ISSUE THREAD

**Issue by rithika212k3** [hasmithagunda123/ALL_INDIA_HACKATHON#71]
Hi @hasmithagunda123,
I would like to add thanks to the contributor section and support section to the readme doc. Can you please assign this issue to me?
It makes the document look more beautiful and it shows your love towards the contributors.
screenshot is attached below. In this way, I want to make changes at the end of the readme document.
![tnxs_support](https://github.com/hasmithagunda123/ALL_INDIA_HACKATHON/assets/158501895/385189b3-4168-44c6-872c-42dbad14272d)

**Comment by rithika212k3** [comment]
Thank you for assigning me the issue.😊

**Comment by rithika212k3** [comment]
I have opened the PR #78. Can you please check that out @hasmithagunda123?

**Comment by rithika212k3** [comment]
@hasmithagunda123 Can you update the Development and close the issue as the PR got merged already?

**Comment by hasmithagunda123** [comment]
closed by #89
