### ISSUE TITLE
Missing contribute.md file.

### ISSUE THREAD

**Issue by SAISUPRIYAPAVARALA** [hasmithagunda123/ALL_INDIA_HACKATHON#8]
I am a GSSoc'24 contributor. I would like to add this file. Could you please assign this to me?

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by MohanRamSridhar** [comment]
can you assign this task to me. I have already done the Readme for this repo and would like to contribute further

**Comment by alishasingh06** [comment]
@hasmithagunda123 please assign this task to me

**Comment by anoushkaacc** [comment]
@hasmithagunda123 i would like to work for this issue under GSSOC'24.

**Comment by ArismitaM** [comment]
I would like to work on this, please assign this to me

**Comment by abizer007** [comment]
I would like to work on this please assign this to me

**Comment by ArismitaM** [comment]
@hasmithagunda123, in the label level 1, could you please remove the space-bar between 'level' and '1'. Only if the label is of the form 'level1', will our contributions towards this task fetch us points towards the leaderboard of gssoc. Thank you
