### ISSUE TITLE
[Documentation Update]: adding requirements.txt 

### ISSUE THREAD

**Issue by Khushalsarode** [hasmithagunda123/ALL_INDIA_HACKATHON#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

NO file for package management 

### Suggested Change

Adding an requirements.txt with required packages to run

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I want to work on this issue

**Comment by hasmithagunda123** [comment]
what do u want to include in requirements.txt could u ellaborate

**Comment by hasmithagunda123** [comment]
packages were already mentioned in the documentation
